[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    pololu/QTRSensors @ ^4.0.0
    adafruit/Adafruit_VL53L0X
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    madhephaestus/ESP32Servo @ ^3.0.5
; platform_packages = 
;     framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
   