[env:esp32dev]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    pololu/QTRSensors @ ^4.0.0
    adafruit/Adafruit_VL53L0X
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    adafruit/Adafruit MPU6050